### ISSUE TITLE
variance within a Voronoicell

### ISSUE THREAD

**Issue by lulu1315** [MarcSpicker/LindeBuzoGrayStippling#1]
hello and thank you for the code.
in the paper you are talking about using the variance to represent small features.
is this implemented ? 
for the moment I understand you are getting the size by interpolating between min and maxsize using sqrt(sumdensity/area).
what would be the right way to get the variance over a Voronoi cell ?
thanks in advance
luc

**Comment by MarcSpicker** [comment]
Hi and thanks for your interest in the code!

It is correct that in this version the point size is determined by the interpolating between min and max size according to the average density (meaning brightness) using this function:
`float stippleSize(const VoronoiCell &cell, const Params &params)`

In the paper, we also describe using the variance of the cell instead. While this is currently not implemented, it can easily be done with a few lines of code:

1. Add a new field variance to the Voronoi cell data structure in `voronoicell.h`
2. Compute variance during aggregation where other quantities are currently determined, meaning line 43ff in `voronoicell.cpp`. Here you can use [Welford's method](http://jonisalonen.com/2013/deriving-welfords-method-for-computing-variance/)
3. Use the variance information to change the way the point size is determined (according to your own wishes) in `lbgstippling.cpp`, using the function mentioned in the beginning.

Hope that helps!

**Comment by lulu1315** [comment]
hello Marc.
thanks a lot for the info.
I'll try that.
cheers

**Comment by lulu1315** [comment]
hello Marc.just to let you know that I've done some videos with your code.you can see the latest here : https://www.youtube.com/watch?v=93dm7nw29KY&feature=youtu.be
